import Head from "next/head";

import HomePage from "@/components/HomePage";
import AuthShowcase from "@/components/AuthShowcase";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>EStore</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
        {/* <CarouselProduct /> */}
      </main>
    </>
  );
}
