import { NavBar } from "@/components";
import { ProductViews } from "@/components/ProductView";
import { useAppSelector } from "@/store/hook";
import { Head } from "next/document";
import React, { useMemo } from "react";

function SearchPage() {
  const { products, searchText } = useAppSelector((state) => state.product);

  const dbProducts = useMemo(() => {
    return products.filter((p) => p.name.includes(searchText));
  }, [searchText]);

  return (
    <>
      {/* <Head>
        <title>EStore</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <main> */}
      <NavBar />
      <div>
        <ProductViews allProducts={dbProducts} />
      </div>
      {/* </main> */}
    </>
  );
}

export default SearchPage;
