import { NavBar, SearchResults } from "@/components";
import { ProductViews } from "@/components/ProductView";
import { useAppSelector } from "@/store/hook";
import { Head } from "next/document";
import React, { useMemo } from "react";

function SearchPage() {
  const { searchedProduct } = useAppSelector((state) => state.product);
  console.log("hi", searchedProduct);

  return (
    <>
      {/* <Head>
        <title>EStore</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <main> */}
      {/* <NavBar /> */}
      <div>
        <ProductViews allProducts={searchedProduct} />
        {/* <SearchResults /> */}
      </div>
      {/* </main> */}
    </>
  );
}

export default SearchPage;
